[project]
name = "okx-reader"
version = "0.1.0"
description = "A NiceGUI app to display OKX open positions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=2.24.1",
    "okx>=2.1.2",
    "python-okx>=0.4.0",
]
